<%@ Page Title="" Language="C#" MasterPageFile="~/Site.Master" AutoEventWireup="true" CodeBehind="ManageProjectGroup.aspx.cs" Inherits="FYPMSWebsite.Student.ManageProjectGroup" %>
<asp:Content ID="Content1" ContentPlaceHolderID="MainContent" runat="server">
    <script type='text/javascript'>
        function clearText(source) {
            source.value = "";
        }
    </script>
    <div class="form-horizontal">
        <h4><span style="text-decoration: underline; color: #00008B" class="h4"><strong>Manage Project Group</strong></span></h4>
        <asp:Label ID="lblResultMessage" runat="server" Font-Bold="True" CssClass="label" Font-Names="Arial Narrow" Font-Size="Small"></asp:Label>
        <asp:Panel ID="pnlAddGroupMember" runat="server" Visible="False">
            <hr />
            <!-- Student input controls -->
            <div class="form-group" role="row">
                <asp:Label runat="server" Text="Student username:" CssClass="control-label col-xs-2" AssociatedControlID="txtUsername" Font-Names="Arial" Font-Size="Small"></asp:Label>
                <div class="col-xs-2">
                    <asp:TextBox ID="txtUsername" runat="server" CssClass="form-control input-sm" MaxLength="15" Wrap="False" 
                        onclick='clearText(this)' ValidationGroup="UsernameValidation" Font-Names="Arial" Font-Size="Small"></asp:TextBox>
                </div>
                <div class="col-xs-2">
                    <asp:Button ID="btnAddGroupMember" runat="server" Text="Add Group Member" CssClass="btn-sm"
                        ValidationGroup="UsernameValidation" OnClick="BtnAddGroupMember_Click" Font-Names="Arial" Font-Size="Small" />
                </div>
                <div class="col-xs-offset-2 col-xs-10">
                    <asp:RequiredFieldValidator runat="server" ErrorMessage="A username is required." ControlToValidate="txtUsername"
                        CssClass="text-danger" Display="Dynamic" EnableClientScript="True" ValidationGroup="UsernameValidation" Font-Names="Arial" Font-Size="Small"></asp:RequiredFieldValidator>
                </div>
                <div class="col-xs-offset-2 col-xs-10">
                    <asp:CustomValidator ID="CvValidateNewMember" runat="server" ErrorMessage=""
                        ControlToValidate="txtUsername" CssClass="text-danger" Display="Dynamic" EnableClientScript="True"
                        OnServerValidate="CvValidateNewMember_ServerValidate" ValidationGroup="UsernameValidation" Font-Names="Arial" Font-Size="Small"></asp:CustomValidator>
                </div>
            </div>
            <div class="form-group" role="row">
            </div>
        </asp:Panel>
        <!-- Group member display -->
        <asp:Panel ID="pnlGroupMembers" runat="server" Visible="False">
            <hr />
            <h5><span style="text-decoration: underline; color: #00008B" class="h5 col-xs-offset-1 "><strong>Group Members</strong></span></h5>
            <div class="form-group" role="row">
                <div class="col-xs-offset-1">
                    <asp:GridView ID="gvGroupMembers" runat="server" CssClass="table-condensed" BorderStyle="Solid"
                        CellPadding="0" Font-Names="Arial" Font-Size="Small" AutoGenerateDeleteButton="True" DeleteText="Remove"
                        OnRowDataBound="GvGroupMembers_RowDataBound" OnRowDeleting="GvGroupMembers_RowDeleting">
                    </asp:GridView>
                </div>
            </div>
        </asp:Panel>
        <asp:Panel ID="pnlCreateButton" runat="server" Visible="False">
            <hr />
            <asp:Button ID="btnCreateGroup" runat="server" Text="Create Group" OnClick="BtnCreateGroup_Click" Font-Names="Arial" Font-Size="Small" />
        </asp:Panel>
    </div>
</asp:Content>
