using System;
using System.Data;
using System.Web;
using System.Web.UI;
using System.Windows.Forms;
using System.Web.UI.WebControls;
using System.Collections.Generic;
using FYPMSWebsite.App_Code;
using static FYPMSWebsite.Global;

namespace FYPMSWebsite.Student
{
    public partial class ManageProjectGroup : Page
    {
        //*******************************************
        // Uses TODO 20, 25, 29, 30, 31, 32, 33, 34 *
        //*******************************************
        private readonly FYPMSDB myFYPMSDB = new FYPMSDB();
        private readonly DBHelperMethods myDBHelpers = new DBHelperMethods();
        private readonly HelperMethods myHelpers = new HelperMethods();
        private readonly SharedDBAccess mySharedDBAccess = new SharedDBAccess();
        private DataTable dtMemberRecord = new DataTable();
        private DataTable dtGroupMembers = new DataTable();
        private readonly int maxMembers = 4;
        private readonly string loggedinUsername = HttpContext.Current.User.Identity.Name;

        /***** Private Methods *****/

        private void AddGroupMember(string groupId, string username)
        {
            lblResultMessage.Visible = false;

            //***************
            // Uses TODO 33 *
            //***************
            if (myFYPMSDB.AddStudentToGroup(groupId, username))
            {
                PopulateGroupMembers(groupId);
                pnlGroupMembers.Visible = true;
            }
            else
            {
                myHelpers.DisplayMessage(lblResultMessage, sqlError);
            }
        }

        private bool CanGetGroupMemberRecord(string username)
        {
            bool queryResult = false;
            //***************
            // Uses TODO 30 *
            //***************
            dtMemberRecord = myFYPMSDB.GetStudentRecord(username);

            // Attributes expected to be returned by the query result.
            var attributeList = new List<string> { "USERNAME", "NAME", "GROUPID" };

            // Add the logged in student's username and student name to the list of group members if the query result is valid.
            if (myHelpers.IsQueryResultValid("TODO 30", dtMemberRecord, attributeList, lblResultMessage))
            {
                queryResult = true;
            }
            return queryResult;
        }

        private void PopulateGroupMembers(string groupId)
        {
            gvGroupMembers.AutoGenerateDeleteButton = false;
            pnlAddGroupMember.Visible = false;

            // *** Uses TODO 20 in SharedDBAccess ***
            dtGroupMembers = mySharedDBAccess.GetProjectGroupMembers(groupId, lblResultMessage);

            if (dtGroupMembers != null)
            {
                if (dtGroupMembers.Rows.Count != 0)
                {
                    // *** Uses TODO 25 in SharedDBAccess ***
                    string isAssigned = mySharedDBAccess.IsGroupAssigned(groupId, lblResultMessage);
                    if (isAssigned != "SQL_ERROR")
                    {
                        if (isAssigned == "true")
                        {
                            myHelpers.DisplayMessage(lblResultMessage, "The group cannot be changed as it is assigned to an FYP.");
                        }
                        else
                        {
                            // *** Uses TODO 29 in SharedDBAccess ***
                            DataTable dtProjectsInterestedIn = mySharedDBAccess.GetFYPsGroupHasIndicatedInterestIn(groupId, lblResultMessage);
                            if (dtProjectsInterestedIn != null)
                            {
                                // Determine if the group has indicated an interest in any FYP.
                                if (dtProjectsInterestedIn.Rows.Count == 0)
                                {
                                    gvGroupMembers.AutoGenerateDeleteButton = true;
                                    pnlAddGroupMember.Visible = true;
                                    // Reset the username textbox.
                                    txtUsername.Text = "";
                                }
                                else // The group has indicated an interest in an FYP.
                                {
                                    myHelpers.DisplayMessage(lblResultMessage, "The group cannot be changed as it has indicated an interest in one or more FYPs.");
                                }
                            }
                            else // An SQL error occurred.
                            {
                                return;
                            }
                        }
                        // If the group is at maximimum size, hide the add group member panel.
                        if (dtGroupMembers.Rows.Count == maxMembers)
                        {
                            pnlAddGroupMember.Visible = false;
                        }
                        ViewState["memberCount"] = dtGroupMembers.Rows.Count;
                        gvGroupMembers.DataSource = dtGroupMembers;
                        gvGroupMembers.DataBind();
                        pnlGroupMembers.Visible = true;
                    }
                }
                else // Nothing was retrieved. Should not happen.
                {
                    myHelpers.DisplayMessage(lblResultMessage, "*** Database error: The project group has no members. Please rerun the Task3DB.sql script file.");
                }
            }
        }

        private void RemoveGroupMember(string selectedUsername, string groupId)
        {
            //***************
            // Uses TODO 34 *
            //***************
            if (myFYPMSDB.RemoveMemberFromGroup(selectedUsername))
            {
                // Delete the project group if the last member has been removed.
                if (gvGroupMembers.Rows.Count == 1)
                {
                    //***************
                    // Uses TODO 32 *
                    //***************
                    if (myFYPMSDB.DeleteProjectGroup(groupId))
                    {
                        myHelpers.DisplayMessage(lblResultMessage, "You are not a member of any project group.");
                        txtUsername.Text = selectedUsername;
                        
                        pnlCreateButton.Visible = true;
                    }
                    else // An SQL error occurred.
                    {
                        myHelpers.DisplayMessage(lblResultMessage, sqlError);
                        pnlCreateButton.Visible = false;
                    }
                    pnlGroupMembers.Visible = false;
                    pnlAddGroupMember.Visible = false;
                }
                else
                {
                    // If the removed user is the loggedin user, then do not display group members.
                    if (selectedUsername != loggedinUsername)
                    {
                        PopulateGroupMembers(groupId);
                    }
                    else
                    {
                        myHelpers.DisplayMessage(lblResultMessage, "You are not a member of any project group.");
                        pnlAddGroupMember.Visible = false;
                        pnlGroupMembers.Visible = false;
                    }
                }
            }
            else // An SQL error occurred.
            {
                myHelpers.DisplayMessage(lblResultMessage, sqlError);
            }
        }

        /***** Protected Methods *****/

        protected void BtnAddGroupMember_Click(object sender, EventArgs e)
        {
            if (Page.IsValid)
            {
                string groupId = ViewState["groupId"].ToString();
                if (groupId != null)
                {
                    AddGroupMember(groupId, txtUsername.Text);
                }
                else // Group id is not assigned. Should not happen.
                {
                    myHelpers.DisplayMessage(lblResultMessage, "*** Database error: Cannot get the group id in Student\\ManageProjectGroup. Please report to 3311rep.");
                }
            }
        }

        protected void BtnCreateGroup_Click(object sender, EventArgs e)
        {
            if (Page.IsValid)
            {
                // This is a new group so create a new project group.
                string groupId = myDBHelpers.GetNextTableId("ProjectGroup", "groupId", lblResultMessage);
                if (groupId != "") // If the group id is empty, an error occurred getting a new group id.
                {
                    //***************
                    // Uses TODO 31 *
                    //***************
                    if (myFYPMSDB.CreateProjectGroup(groupId))
                    {
                        AddGroupMember(groupId, loggedinUsername);
                        ViewState["groupId"] = groupId;
                        pnlCreateButton.Visible = false;
                        pnlAddGroupMember.Visible = true;
                    }
                    else // An SQL error occurred.
                    {
                        myHelpers.DisplayMessage(lblResultMessage, sqlError);
                    }
                }
            }
        }

        protected void CvValidateNewMember_ServerValidate(object source, ServerValidateEventArgs args)
        {
            // Display the group members if the query result is valid.
            if (CanGetGroupMemberRecord(txtUsername.Text))
            {
                // Check if there is a student with the specified username.
                if (dtMemberRecord.Rows.Count != 0)
                {
                    {
                        // Check if the student is already a member of another group.
                        if (dtMemberRecord.Rows[0]["GROUPID"].ToString() != "")
                        {
                            CvValidateNewMember.ErrorMessage = "The student is a member of another group.";
                            args.IsValid = false;
                        }
                        else // Check if the student has already been added to the group.
                        {
                            foreach (DataRow row in dtGroupMembers.Rows)
                            {
                                if (row["USERNAME"].ToString() == txtUsername.Text)
                                {
                                    CvValidateNewMember.ErrorMessage = "The student is already a member of this group.";
                                    args.IsValid = false;
                                }
                            }
                        }
                    }
                }
                else // No student with this username.
                {
                    CvValidateNewMember.ErrorMessage = "There is no student with this username.";
                    args.IsValid = false;
                }
            }
        }

        protected void GvGroupMembers_RowDataBound(object sender, GridViewRowEventArgs e)
        {
            if (e.Row.Controls.Count == 3)
            {
                int groupIdColumn = myHelpers.GetGridViewColumnIndexByName(sender, "GROUPID", lblResultMessage);

                if (groupIdColumn != -1)
                {
                    e.Row.Cells[groupIdColumn].Visible = false;
                }
            }

            if (e.Row.Controls.Count == 4)
            {
                // Offset by 1 due to Delete column.
                int groupIdColumn = myHelpers.GetGridViewColumnIndexByName(sender, "GROUPID", lblResultMessage) + 1;

                if (groupIdColumn != 0)
                {
                    {
                        e.Row.Cells[groupIdColumn].Visible = false;
                    }
                }
            }
        }

        protected void GvGroupMembers_RowDeleting(object sender, GridViewDeleteEventArgs e)
        {
            string selectedUsername = gvGroupMembers.Rows[e.RowIndex].Cells[1].Text.Trim();
            string groupId = gvGroupMembers.Rows[e.RowIndex].Cells[3].Text;

            if (selectedUsername == loggedinUsername)
            {
                DialogResult dialogResult = MessageBox.Show("If you remove yourself from the group," + Environment.NewLine
                + "you will no longer have access to the group." + Environment.NewLine + "Do you want to proceed?",
                "Remove Group Member", MessageBoxButtons.YesNo);

                switch (dialogResult)
                {
                    // Confirm removal of loggedin user.
                    case DialogResult.Yes:
                        ViewState["groupId"] = "";
                        RemoveGroupMember(selectedUsername, groupId);
                        break;
                    // No action.
                    case DialogResult.No:
                        break;
                }
            }
            else
            {
                RemoveGroupMember(selectedUsername, groupId);
            }
        }

        protected void Page_Load(object sender, EventArgs e)
        {
            if (!Page.IsPostBack)
            {
                if (CanGetGroupMemberRecord(loggedinUsername))
                {
                    if (myDBHelpers.CleanUpProjectGroups(lblResultMessage))
                    {
                        if (dtMemberRecord.Rows.Count != 0)
                        {
                            ViewState["memberCount"] = 0;
                            if (dtMemberRecord.Rows[0]["GROUPID"].ToString() != "")
                            {
                                PopulateGroupMembers(dtMemberRecord.Rows[0]["GROUPID"].ToString());
                            }
                            else
                            {
                                txtUsername.Text = dtMemberRecord.Rows[0]["USERNAME"].ToString();
                                myHelpers.DisplayMessage(lblResultMessage, "You are not a member of any project group.");
                                pnlCreateButton.Visible = true;
                            }
                            ViewState["groupId"] = dtMemberRecord.Rows[0]["GROUPID"].ToString();
                        }
                        else // Nothing was retrieved.
                        {
                            myHelpers.DisplayMessage(lblResultMessage, "*** Database error: The username " + loggedinUsername + " does not exist. Please rerun the Task3DB.sql script file.");
                        }
                    }
                }
            }
        }
    }
}